### ISSUE TITLE
Mostrar una lista de Pokemons

### ISSUE THREAD

**Issue by Ctatianap** [Armando-Lopez/pokedex#3]
Criterios de Aceptación:

• Deben mostrarse los primeros 25 pokemons
• C/U debe aparecer con su foto, nombre, número y tipo.
• Los pokemon deben poder filtrarse por nombre.
• En el listado principal debe aparecer, si el pokemon es una evolunción de otro,
de cuál proviene.

**Comment by Armando-Lopez** [comment]
Bien hecho
